/* 
  Sketch generated by the Arduino IoT Cloud Thing "Mario"
  https://create.arduino.cc/cloud/things/f4fb20c7-c0ff-4075-a198-460fd416a6ea 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int raw_moisture;
  bool watering;
  CloudPercentage moisture;
  String log_message;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#include <Arduino_MKRIoTCarrier.h>
MKRIoTCarrier opla;

const int moistPin = A5;
const float waterAmount = 2;  // liters
const float waterSpeed = 0.045; // liters/sec
const float waterTime = waterAmount / waterSpeed;  // seconds
unsigned long startedWatering;

void setup() {
  Serial.begin(9600);
  delay(1500);

  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(4);
  ArduinoCloud.printDebugInfo();
  
  // Initialize Oplà
  CARRIER_CASE = true;
  opla.begin();

  // Make sure the pump is not running
  stopWatering();
}

void loop() {
  ArduinoCloud.update();
  
  // Read the sensor and convert its value to a percentage 
  // (0% = dry; 100% = wet)
  raw_moisture = analogRead(moistPin);
  moisture = map(raw_moisture, 780, 1023, 100, 0);
  
  // Stop watering after the configured duration
  if (watering && (millis() - startedWatering) >= waterTime*1000) {
    stopWatering();
  }
  
  // Handle button presses to start/stop watering
  opla.Buttons.update();
  if (opla.Buttons.onTouchDown(TOUCH0)) {
    if (watering) {
      stopWatering();
    } else {
      startWatering();
    }
  }
  
  delay(200);
}

// This function is triggered whenever the server sends a change event,
// which means that someone changed a value remotely and we need to do
// something.
void onWateringChange() {
  if (watering) {
    startWatering();
  } else {
    stopWatering();
  }
}

void startWatering () {
  watering = true;
  log_message = "Start watering";
  startedWatering = millis();
  opla.Relay2.open();
  opla.leds.setPixelColor(0, 0 , 50 , 0);
  opla.leds.show();
}

void stopWatering () {
  watering = false;
  log_message = "Stop watering";
  opla.Relay2.close();
  opla.leds.setPixelColor(0, 50 , 0 , 0);
  opla.leds.show();
}





